// Generated by https://quicktype.io

export interface NewFlight {
    name:           string;
    brand:          string;
    flyType:        number;
    minutesFlyTime: number;
    flyDate:        string;
    latitude:       string;
    longitude:      string;
}
